# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\"+\n\x08TodoItem\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty2P\n\x0bTodoService\x12\x1f\n\x07\x41\x64\x64Item\x12\t.TodoItem\x1a\t.TodoItem\x12 \n\tListItems\x12\x06.Empty\x1a\t.TodoItem0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODOITEM']._serialized_start=14
  _globals['_TODOITEM']._serialized_end=57
  _globals['_EMPTY']._serialized_start=59
  _globals['_EMPTY']._serialized_end=66
  _globals['_TODOSERVICE']._serialized_start=68
  _globals['_TODOSERVICE']._serialized_end=148
# @@protoc_insertion_point(module_scope)
